# SIMULINDEX

## Importamos librerías

In [1]:
import pandas as pd
import plotly.express as px

## Importamos el fichero excel

In [2]:
df_in=pd.read_excel('data.xlsx')
df_in=df_in.set_index('fecha')
df_in

,año,mes,mes_nombre,dia,dia_semana,hora,dh_6p,dh_3p,pmh,ssaa,...,perd_2.0,perd_3.0,perd_6.1,pyc_2.0,pyc_3.0,pyc_6.1,precio_2.0,precio_3.0,precio_6.1,demanda_GWh
fecha,,,,,,,,,,,,,,,,,,,,,
2024-07-31,2024,7,julio,31,miércoles,23,P2,P2,116.98,8.58,...,0.155610,0.167065,0.064917,27.963,30.938,21.531,180.671803,185.620453,162.755647,31.94
2024-07-31,2024,7,julio,31,miércoles,22,P2,P2,132.40,9.82,...,0.157365,0.168950,0.065649,27.963,30.938,21.531,200.467119,205.629014,180.869352,34.43
2024-07-31,2024,7,julio,31,miércoles,21,P1,P1,142.48,11.53,...,0.150793,0.149890,0.060498,76.974,48.443,35.204,263.209342,234.909623,206.799220,35.43
2024-07-31,2024,7,julio,31,miércoles,20,P1,P1,117.53,14.44,...,0.149475,0.148580,0.059969,76.974,48.443,35.204,237.287386,209.008508,183.004033,35.51
2024-07-31,2024,7,julio,31,miércoles,19,P1,P1,111.14,8.31,...,0.148453,0.147564,0.059559,76.974,48.443,35.204,222.554981,194.287895,169.484129,35.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-01,2023,1,enero,1,domingo,4,P6,P3,0.00,37.79,...,0.278267,0.278267,0.119037,3.175,2.370,1.426,57.464799,56.659799,49.575884,0.00
2023-01-01,2023,1,enero,1,domingo,3,P6,P3,0.00,36.05,...,0.271627,0.271627,0.116196,3.175,2.370,1.426,54.962933,54.157933,47.495040,0.00
2023-01-01,2023,1,enero,1,domingo,2,P6,P3,0.00,36.09,...,0.260780,0.260780,0.111556,3.175,2.370,1.426,54.615027,53.810027,47.369445,0.00
2023-01-01,2023,1,enero,1,domingo,1,P6,P3,0.00,24.80,...,0.246510,0.246510,0.105451,3.175,2.370,1.426,39.805191,39.000191,34.476832,0.00
2023-01-01,2023,1,enero,1,domingo,0,P6,P3,0.00,24.02,...,0.236678,0.236678,0.101246,3.175,2.370,1.426,38.576636,37.771636,33.498255,0.00

In [3]:
df_out=df_in.loc[:,['spot','precio_2.0', 'precio_3.0','precio_6.1']]

df_out

              spot  precio_2.0  precio_3.0  precio_6.1
fecha
2024-07-31  116.98  180.671803  185.620453  162.755647
2024-07-31  132.40  200.467119  205.629014  180.869352
2024-07-31  142.48  263.209342  234.909623  206.799220
2024-07-31  117.53  237.287386  209.008508  183.004033
2024-07-31  111.14  222.554981  194.287895  169.484129
...            ...         ...         ...         ...
2023-01-01    0.00   57.464799   56.659799   49.575884
2023-01-01    0.00   54.962933   54.157933   47.495040
2023-01-01    0.00   54.615027   53.810027   47.369445
2023-01-01    0.00   39.805191   39.000191   34.476832
2023-01-01    0.00   38.576636   37.771636   33.498255

[13877 rows x 4 columns]

In [4]:
df_mes=df_out.resample('M').mean()
df_mes

                  spot  precio_2.0  precio_3.0  precio_6.1
fecha
2023-01-31   69.551734  132.107087  127.081533  110.739624
2023-02-28  133.473006  203.418183  198.283942  175.085261
2023-03-31   89.695626  155.448480  143.114663  126.059171
2023-04-30   73.733375  133.394152  112.740967  100.922483
2023-05-31   74.208293  131.594760  109.738736   99.511110
2023-06-30   93.021694  151.009446  132.125739  120.072866
2023-07-31   90.468763  145.717972  140.648961  125.143273
2023-08-31   96.045659  153.493625  135.191190  122.739638
2023-09-30  103.340444  162.223748  144.159600  131.144549
2023-10-31   89.311944  152.387234  131.569941  119.605660
2023-11-30   63.445639  124.642846  112.921614   99.553365
2023-12-31   72.173992  129.875524  125.464413  109.264832
2024-01-31   74.100094  134.256787  128.934361  111.682119
2024-02-29   39.998966   93.160661   87.618829   74.882915
2024-03-31   20.305209   70.933743   58.292180   50.366618
2024-04-30   13.670042   70.657662   47.977428   42.968303
2024-05-31   30.398602   86.001248   63.973384   57.697828
2024-06-30   56.079778  110.625913   93.253090   84.511996
2024-07-31   72.312836  128.119809  122.485850  108.191691

In [5]:
df_hist=df_mes.tail(12).copy()
df_hist['precio_2.0']=round(df_hist['precio_2.0']/10,1)
df_hist['precio_3.0']=round(df_hist['precio_3.0']/10,1)
df_hist['precio_6.1']=round(df_hist['precio_6.1']/10,1)
df_hist['spot']=round(df_hist['spot'],2)
df_hist

              spot  precio_2.0  precio_3.0  precio_6.1
fecha
2023-08-31   96.05        15.3        13.5        12.3
2023-09-30  103.34        16.2        14.4        13.1
2023-10-31   89.31        15.2        13.2        12.0
2023-11-30   63.45        12.5        11.3        10.0
2023-12-31   72.17        13.0        12.5        10.9
2024-01-31   74.10        13.4        12.9        11.2
2024-02-29   40.00         9.3         8.8         7.5
2024-03-31   20.31         7.1         5.8         5.0
2024-04-30   13.67         7.1         4.8         4.3
2024-05-31   30.40         8.6         6.4         5.8
2024-06-30   56.08        11.1         9.3         8.5
2024-07-31   72.31        12.8        12.2        10.8

In [6]:
def graf_hist(omip):
    colores_precios = {'precio_2.0': 'goldenrod', 'precio_3.0': 'darkred', 'precio_6.1': 'blue'}
    graf_hist=px.scatter(df_hist,x='spot',y=['precio_2.0','precio_3.0','precio_6.1'], trendline='ols',
                labels={'value':'c€/kWh','variable':'Precios s/ ATR','spot':'Precio medio mercado mayorista €/MWh'},
                height=500,
                color_discrete_map=colores_precios
    )
    
    trend_results = px.get_trendline_results(graf_hist)

    #obtención del precio 2.0 simulado a partir del gráfico de tendencia 2.0
    params_20 = trend_results[trend_results['Precios s/ ATR']=='precio_2.0'].px_fit_results.iloc[0].params
    intercept_20, slope_20 = params_20[0], params_20[1]
    simul_20=round(intercept_20+slope_20*omip,1)
                
    #obtención del precio 3.0 simulado a partir del gráfico de tendencia 3.0
    params_30 = trend_results[trend_results['Precios s/ ATR']=='precio_3.0'].px_fit_results.iloc[0].params
    intercept_30, slope_30 = params_30[0], params_30[1]
    simul_30=round(intercept_30+slope_30*omip,1)
    
    #obtención del precio 6.1 simulado a partir del gráfico de tendencia 6.1
    params_61 = trend_results[trend_results['Precios s/ ATR']=='precio_6.1'].px_fit_results.iloc[0].params
    intercept_61, slope_61 = params_61[0], params_61[1]
    simul_61=round(intercept_61+slope_61*omip,1)

    graf_hist.add_scatter(x=[omip],y=[simul_20], mode='markers', 
        marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='goldenrod')),
        name='Simul 2.0',
        text='Simul 2.0'
    )
    graf_hist.add_scatter(x=[omip],y=[simul_30], mode='markers', 
        marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='darkred')),
        name='Simul 3.0',
        text='Simul 3.0'
    )
    graf_hist.add_scatter(x=[omip],y=[simul_61], mode='markers', 
        marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='blue')),
        name='Simul 6.1',
        text='Simul 6.1'
    )
    graf_hist.add_shape(
        type='line',
        x0=omip,
        y0=0,
        x1=omip,
        y1=simul_20,
        line=dict(color='grey', width=1,dash='dash'),
    )
    return graf_hist,simul_20,simul_30,simul_61