# Telemindex

## Importamos librerías

In [98]:
#En pruebas: Uso de la variables mes_seleccionado definida en el archivo 'globals.py'

In [99]:
import pandas as pd
import plotly.express as px
#import globals

## Importamos el fichero excel

In [100]:
df_in=pd.read_excel('data.xlsx')
df_in=df_in.set_index('fecha')
df_in

,año,mes,mes_nombre,dia,dia_semana,hora,dh_6p,dh_3p,pmh,ssaa,...,perd_2.0,perd_3.0,perd_6.1,pyc_2.0,pyc_3.0,pyc_6.1,precio_2.0,precio_3.0,precio_6.1,demanda_GWh
fecha,,,,,,,,,,,,,,,,,,,,,
2024-06-30,2024,6,junio,30,domingo,23,P6,P3,100.92,19.65,...,0.175460,0.175460,0.075058,2.752,2.192,1.276,151.865620,151.305620,138.080107,25.44
2024-06-30,2024,6,junio,30,domingo,22,P6,P3,103.22,9.64,...,0.170519,0.170519,0.072944,2.752,2.192,1.276,142.099769,141.539769,129.424482,26.91
2024-06-30,2024,6,junio,30,domingo,21,P6,P3,101.64,10.38,...,0.169573,0.169573,0.072539,2.752,2.192,1.276,140.993921,140.433921,128.463548,26.64
2024-06-30,2024,6,junio,30,domingo,20,P6,P3,59.10,23.59,...,0.170183,0.170183,0.072800,2.752,2.192,1.276,106.227154,105.667154,96.556071,25.73
2024-06-30,2024,6,junio,30,domingo,19,P6,P3,46.62,12.75,...,0.168079,0.168079,0.071900,2.752,2.192,1.276,78.401891,77.841891,71.108656,24.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-01,2023,1,enero,1,domingo,4,P6,P3,0.00,37.79,...,0.278267,0.278267,0.119037,3.175,2.370,1.426,57.464799,56.659799,49.575884,0.00
2023-01-01,2023,1,enero,1,domingo,3,P6,P3,0.00,36.05,...,0.271627,0.271627,0.116196,3.175,2.370,1.426,54.962933,54.157933,47.495040,0.00
2023-01-01,2023,1,enero,1,domingo,2,P6,P3,0.00,36.09,...,0.260780,0.260780,0.111556,3.175,2.370,1.426,54.615027,53.810027,47.369445,0.00
2023-01-01,2023,1,enero,1,domingo,1,P6,P3,0.00,24.80,...,0.246510,0.246510,0.105451,3.175,2.370,1.426,39.805191,39.000191,34.476832,0.00
2023-01-01,2023,1,enero,1,domingo,0,P6,P3,0.00,24.02,...,0.236678,0.236678,0.101246,3.175,2.370,1.426,38.576636,37.771636,33.498255,0.00

In [101]:
df_out=df_in.loc[:,['spot','precio_2.0', 'precio_3.0','precio_6.1']]

df_out

              spot  precio_2.0  precio_3.0  precio_6.1
fecha
2024-06-30  100.92  151.865620  151.305620  138.080107
2024-06-30  103.22  142.099769  141.539769  129.424482
2024-06-30  101.64  140.993921  140.433921  128.463548
2024-06-30   59.10  106.227154  105.667154   96.556071
2024-06-30   46.62   78.401891   77.841891   71.108656
...            ...         ...         ...         ...
2023-01-01    0.00   57.464799   56.659799   49.575884
2023-01-01    0.00   54.962933   54.157933   47.495040
2023-01-01    0.00   54.615027   53.810027   47.369445
2023-01-01    0.00   39.805191   39.000191   34.476832
2023-01-01    0.00   38.576636   37.771636   33.498255

[13133 rows x 4 columns]

In [102]:
df_mes=df_out.resample('M').mean()
df_mes

                  spot  precio_2.0  precio_3.0  precio_6.1
fecha
2023-01-31   69.551734  132.107087  127.081533  110.739624
2023-02-28  133.473006  203.418183  198.283942  175.085261
2023-03-31   89.695626  155.448480  143.114663  126.059171
2023-04-30   73.733375  133.394152  112.740967  100.922483
2023-05-31   74.208293  131.594760  109.738736   99.511110
2023-06-30   93.021694  151.009446  132.125739  120.072866
2023-07-31   90.468763  145.717972  140.648961  125.143273
2023-08-31   96.045659  153.493625  135.191190  122.739638
2023-09-30  103.340444  162.223748  144.159600  131.144549
2023-10-31   89.311944  152.387234  131.569941  119.605660
2023-11-30   63.445639  124.642846  112.921614   99.553365
2023-12-31   72.173992  129.875524  125.464413  109.264832
2024-01-31   74.100094  134.256787  128.934361  111.682119
2024-02-29   39.998966   93.160661   87.618829   74.882915
2024-03-31   20.305209   70.933743   58.292180   50.366618
2024-04-30   13.670042   70.657662   47.977428   42.968303
2024-05-31   30.398602   86.001248   63.973384   57.697828
2024-06-30   56.079778  110.625913   93.253090   84.511996

In [103]:
df_hist=df_mes.tail(12).copy()
df_hist['precio_2.0']=round(df_hist['precio_2.0']/10,1)
df_hist['precio_3.0']=round(df_hist['precio_3.0']/10,1)
df_hist['precio_6.1']=round(df_hist['precio_6.1']/10,1)
df_hist['spot']=round(df_hist['spot'],2)
df_hist

              spot  precio_2.0  precio_3.0  precio_6.1
fecha
2023-07-31   90.47        14.6        14.1        12.5
2023-08-31   96.05        15.3        13.5        12.3
2023-09-30  103.34        16.2        14.4        13.1
2023-10-31   89.31        15.2        13.2        12.0
2023-11-30   63.45        12.5        11.3        10.0
2023-12-31   72.17        13.0        12.5        10.9
2024-01-31   74.10        13.4        12.9        11.2
2024-02-29   40.00         9.3         8.8         7.5
2024-03-31   20.31         7.1         5.8         5.0
2024-04-30   13.67         7.1         4.8         4.3
2024-05-31   30.40         8.6         6.4         5.8
2024-06-30   56.08        11.1         9.3         8.5

graf_hist=px.scatter(df_hist,x='spot',y=['precio_2.0','precio_3.0','precio_6.1'], trendline='ols',
                labels={'value':'c€/kWh','variable':'Precios s/ ATR','spot':'Precio medio mercado mayorista €/MWh'},
                height=500,
                
                )

In [ ]:
def graf_hist(omip):
    graf_hist=px.scatter(df_hist,x='spot',y=['precio_2.0','precio_3.0','precio_6.1'], trendline='ols',
                labels={'value':'c€/kWh','variable':'Precios s/ ATR','spot':'Precio medio mercado mayorista €/MWh'},
                height=500,
    )
    
    trend_results = px.get_trendline_results(graf_hist)

    #obtención del precio 2.0 simulado a partir del gráfico de tendencia 2.0
    params_20 = trend_results[trend_results['Precios s/ ATR']=='precio_2.0'].px_fit_results.iloc[0].params
    intercept_20, slope_20 = params_20[0], params_20[1]
    simul_20=round(intercept_20+slope_20*omip,1)
                
    #obtención del precio 3.0 simulado a partir del gráfico de tendencia 3.0
    params_30 = trend_results[trend_results['Precios s/ ATR']=='precio_3.0'].px_fit_results.iloc[0].params
    intercept_30, slope_30 = params_30[0], params_30[1]
    simul_30=round(intercept_30+slope_30*omip,1)
    
    #obtención del precio 6.1 simulado a partir del gráfico de tendencia 6.1
    params_61 = trend_results[trend_results['Precios s/ ATR']=='precio_6.1'].px_fit_results.iloc[0].params
    intercept_61, slope_61 = params_61[0], params_61[1]
    simul_61=round(intercept_61+slope_61*omip,1)

    graf_hist.add_scatter(x=[omip],y=[simul_20], mode='markers', 
        marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='blue')),
        name='Simul 2.0',
        text='Simul 2.0'
    )
    graf_hist.add_scatter(x=[omip],y=[simul_30], mode='markers', 
        marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='red')),
        name='Simul 3.0',
        text='Simul 3.0'
    )
    graf_hist.add_scatter(x=[omip],y=[simul_61], mode='markers', 
        marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='green')),
        name='Simul 6.1',
        text='Simul 6.1'
    )
    graf_hist.add_shape(
        type='line',
        x0=omip,
        y0=0,
        x1=omip,
        y1=simul_20,
        line=dict(color='grey', width=1,dash='dash'),
    )
    return graf_hist,simul_20,simul_30,simul_61

#graf_hist()
graf_hist()

omip=50

trend_results = px.get_trendline_results(graf_hist())
trend_results

#obtención del precio 2.0 simulado a partir del gráfico de tendencia 2.0
params_20 = trend_results[trend_results['Precios s/ ATR']=='precio_2.0'].px_fit_results.iloc[0].params
intercept_20, slope_20 = params_20[0], params_20[1]
simul_20=intercept_20+slope_20*omip

#obtención del precio 3.0 simulado a partir del gráfico de tendencia 3.0
params_30 = trend_results[trend_results['Precios s/ ATR']=='precio_3.0'].px_fit_results.iloc[0].params
intercept_30, slope_30 = params_30[0], params_30[1]
simul_30=intercept_30+slope_30*omip

#obtención del precio 6.1 simulado a partir del gráfico de tendencia 6.1
params_61 = trend_results[trend_results['Precios s/ ATR']=='precio_6.1'].px_fit_results.iloc[0].params
intercept_61, slope_61 = params_61[0], params_61[1]
simul_61=round(intercept_61+slope_61*omip,1)

graf_hist.add_scatter(x=[omip],y=[simul_20], mode='markers', 
    marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='blue')),
    name='Simul 2.0',
    text='Simul 2.0'
)
graf_hist.add_scatter(x=[omip],y=[simul_30], mode='markers', 
    marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='red')),
    name='Simul 3.0',
    text='Simul 3.0'
)
graf_hist.add_scatter(x=[omip],y=[simul_61], mode='markers', 
    marker=dict(color='rgba(255, 255, 255, 0)',size=20, line=dict(width=5, color='green')),
    name='Simul 6.1',
    text='Simul 6.1'
)
graf_hist.add_shape(
    type='line',
    x0=omip,
    y0=0,
    x1=omip,
    y1=simul_20,
    line=dict(color='grey', width=1,dash='dash'),
    
)
graf_hist

### Interacción en streamlit: Listado de meses disponibles para usar en un select_box

In [ ]:
lista_meses=df_in['mes_nombre'].unique().tolist()
lista_meses

['junio',
 'mayo',
 'abril',
 'marzo',
 'febrero',
 'enero',
 'diciembre',
 'noviembre',
 'octubre',
 'septiembre',
 'agosto',
 'julio']

In [ ]:
orden_meses = {
    'enero': 1,
    'febrero': 2,
    'marzo': 3,
    'abril': 4,
    'mayo': 5,
    'junio': 6,
    'julio': 7,
    'agosto': 8,
    'septiembre': 9,
    'octubre': 10,
    'noviembre': 11,
    'diciembre': 12
}

In [ ]:
lista_meses=sorted(lista_meses,key=lambda x:orden_meses[x])
lista_meses

['enero',
 'febrero',
 'marzo',
 'abril',
 'mayo',
 'junio',
 'julio',
 'agosto',
 'septiembre',
 'octubre',
 'noviembre',
 'diciembre']

## Telemindex horario para streamlit

In [ ]:
### Inicializamos dffm, que es el la tabla filtrada por el usuario

In [ ]:
def aplicar_margen(mes_seleccionado,margen_aplicado):
    #dffa_copia=dffa
    dffa_copia['precio_2.0']=dffa['precio_2.0'] #+=margen_aplicado #=dffm['precio_2.0']+margen
    dffa_copia['precio_3.0']=dffa['precio_3.0'] #+=margen_aplicado #dffm['precio_3.0']+margen
    dffa_copia['precio_6.1']=dffa['precio_6.1'] #+=margen_aplicado #dffm['precio_6.1']+margen
    dffa_copia['precio_2.0']+=margen_aplicado #=dffm['precio_2.0']+margen
    dffa_copia['precio_3.0']+=margen_aplicado #dffm['precio_3.0']+margen
    dffa_copia['precio_6.1']+=margen_aplicado #dffm['precio_6.1']+margen
    
    filtrar_mes(mes_seleccionado)

    return dffa_copia

### De esta tabla sale el gráfico

### Gráfico de salida para visualizar en streamlit